name = "durwesh-perfume-store"
main = "src/index.js"
compatibility_date = "2024-01-15"

[env.production]
name = "durwesh-perfume-store"

[[env.production.d1_databases]]
binding = "DB"
database_name = "durwesh-perfumes"
database_id = "your-database-id-here"

[env.development]
name = "durwesh-perfume-store-dev"

[[env.development.d1_databases]]
binding = "DB"
database_name = "durwesh-perfumes-dev"
database_id = "your-dev-database-id-here"

# Functions configuration
[[env.production.routes]]
pattern = "yourdomain.com/api/*"
zone_name = "yourdomain.com"

[[env.development.routes]]
pattern = "localhost:8787/api/*"