name = "durwesh-perfume-store"
compatibility_date = "2024-01-15"

[env.production]
name = "durwesh-perfume-store"

[[env.production.d1_databases]]
binding = "DB"
database_name = "durwesh-db"
database_id = "c5d9b184-af24-4cf1-a388-a96b45b60776"

[env.development]
name = "durwesh-perfume-store-dev"

[[env.development.d1_databases]]
binding = "DB"
database_name = "durwesh-db"
database_id = "c5d9b184-af24-4cf1-a388-a96b45b60776"

# Functions configuration for production
[[env.production.routes]]
pattern = "*/api/*"

[[env.development.routes]]
pattern = "localhost:8787/api/*"