name = "durwesh254"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# 👇 Required for Pages projects (this tells Pages where your built site is)
pages_build_output_dir = "dist"

# 👇 Link to your D1 database (already created)
[[d1_databases]]
binding = "DB"
database_name = "durwesh-db"
database_id = "c5d9b184-af24-4cf1-a388-a96b45b60776"
